version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root    # password root MySQL, kamu bisa ganti sesuai keinginan
      MYSQL_DATABASE: bloodwellnessaccount    # nama database sesuai DB_DATABASE di .env
      MYSQL_USER: blooduser                    # username sesuai DB_USERNAME di .env
      MYSQL_PASSWORD: bloodpass123             # password sesuai DB_PASSWORD di .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - storage-data:/var/www/html/storage

    networks:
      - app-network

volumes:
  db-data:
  storage-data:


networks:
  app-network:
    driver: bridge
